{{ if .Values.nfs.mountOptions -}}
{{- $server := .Values.nfs.server -}}
{{- $path := .Values.nfs.path -}}
{{- if (include "nfs.existing-configmap-provided" .) -}}
{{- $server := (include "common.configmap.lookup" (dict "config" .Values.nfs.existingConfigMap.name "key" "server" "defaultValue" .Values.nfs.server "context" $)) -}}
{{- $path := (include "common.configmap.lookup" (dict "config" .Values.nfs.existingConfigMap.name "key" "path" "defaultValue" .Values.nfs.path "context" $)) -}}
{{- end -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ template "nfs-subdir-external-provisioner.fullname" . }}
  labels: 
    {{- include "nfs-subdir-external-provisioner.labels" . | nindent 4 }}
    nfs-subdir-external-provisioner: {{ template "nfs-subdir-external-provisioner.fullname" . }}
spec:
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.storageClass.accessModes }}
  persistentVolumeReclaimPolicy: {{ .Values.nfs.reclaimPolicy }}
  storageClassName: ""
  {{- if .Values.nfs.mountOptions }}
  mountOptions:
    {{- range .Values.nfs.mountOptions }}
    - {{ . }}
    {{- end }}
  {{- end }}
  nfs:
    server: {{ $server }}
    path: {{ $path }}
{{ end -}}
